<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>    
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    
    <!-- Package Metadata -->
    <PackageId>FluentReflection</PackageId>
    <Version>1.0.0</Version>
    <Authors>Rui Santos</Authors>
    <Company>FluentReflection</Company>
    <Description>A fluent, intuitive .NET 10 library designed to simplify unit testing by providing an expressive way to access private, internal, and public members (fields, backing fields, properties, methods) using reflection.</Description>
    <PackageTags>reflection;fluent;private-access;testing;nfluent;tunit;framework</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/ruisantos78/FluentReflection</RepositoryUrl>
  </PropertyGroup>

</Project>
